spring:
  application:
  name: news_management
  datasource:
    url: jdbc:postgresql://${BD_HOST}:${BD_PORT}/${BD_NAME}
    username: ${BD_USERNAME}
    password: ${BD_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


